// src/labor-optimizer/src/lib/components/layout/Sidebar.svelte
<script lang="ts">
  import { page } from '$app/stores';

  let { open = $bindable(true) } = $props();

  const sections = [
    {
      category: 'OPERATIONS',
      items: [
        { href: '/dashboard', label: 'Dashboard' },
        { href: '/schedule', label: 'Schedule' },
        { href: '/employees', label: 'Employees' },
      ],
    },
    {
      category: 'ANALYTICS',
      items: [
        { href: '/forecasting', label: 'Forecasting' },
        { href: '/labor-cost', label: 'Labor Cost' },
        { href: '/reports', label: 'Reports' },
      ],
    },
    {
      category: 'COMPLIANCE',
      items: [
        { href: '/compliance', label: 'Compliance' },
        { href: '/settings', label: 'Settings' },
      ],
    },
  ];

  function isActive(href: string): boolean {
    return $page.url.pathname.startsWith(href);
  }
</script>

{#if open}
<aside class="flex w-56 flex-col bg-sidebar">
  <div class="flex h-16 items-center gap-3 px-6">
    <div class="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10">
      <span class="text-sm font-bold text-white">H</span>
    </div>
    <span class="text-base font-semibold text-white">HELIXO</span>
  </div>

  <nav class="flex-1 px-3 py-4 space-y-6">
    {#each sections as section}
      <div>
        <p class="px-3 mb-2 text-[11px] font-semibold tracking-wider text-sidebar-category uppercase">
          {section.category}
        </p>
        <div class="space-y-0.5">
          {#each section.items as item}
            <a
              href={item.href}
              class="block rounded-md px-3 py-2 text-sm transition-colors
                {isActive(item.href)
                  ? 'bg-sidebar-hover text-sidebar-active font-medium'
                  : 'text-sidebar-text hover:bg-sidebar-hover hover:text-white'}"
            >
              {item.label}
            </a>
          {/each}
        </div>
      </div>
    {/each}
  </nav>
</aside>
{/if}

// src/nahv/frontend/components/Sidebar.tsx
'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const navItems = [
  { href: '/', label: 'Dashboard', icon: '◼' },
  { href: '/leads', label: 'Leads', icon: '◼' },
  { href: '/pipeline', label: 'Pipeline', icon: '◼' },
];

export default function Sidebar() {
  const pathname = usePathname();

  return (
    <aside className="w-56 bg-indigo-900 text-white flex flex-col shrink-0">
      <div className="px-6 py-6 border-b border-indigo-800">
        <div className="flex items-center gap-2">
          <div className="w-7 h-7 bg-indigo-400 rounded-lg flex items-center justify-center text-sm font-bold">N</div>
          <div>
            <h1 className="text-base font-bold leading-tight">Nahv</h1>
            <p className="text-indigo-400 text-xs">Sales & Leads</p>
          </div>
        </div>
      </div>

      <nav className="flex-1 px-3 py-4 space-y-1">
        {navItems.map((item) => {
          const active = pathname === item.href;
          return (
            <Link
              key={item.href}
              href={item.href}
              className={`flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-colors ${
                active
                  ? 'bg-indigo-700 text-white font-medium'
                  : 'text-indigo-300 hover:bg-indigo-800 hover:text-white'
              }`}
            >
              <span className={`w-2 h-2 rounded-sm ${active ? 'bg-indigo-300' : 'bg-indigo-600'}`} />
              {item.label}
            </Link>
          );
        })}
      </nav>

      <div className="px-6 py-4 border-t border-indigo-800">
        <p className="text-indigo-500 text-xs">Nahv v1.0</p>
      </div>
    </aside>
  );
}
